# app.py
from flask import Flask, render_template, request, jsonify
from alert_manager import check_new_alerts
import webbrowser
from flask import Flask, render_template
from flask import send_file
import yaml
import json, os

app = Flask(__name__)

# Load config
with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)["firms"]
TOKENS_FILE = "tokens.json"

@app.route("/map")
def serve_map():
    # This is the HTML map generated by Folium
    return send_file("wildfires_map.html")

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/register_token", methods=["POST"])
def register_token():
    """Save FCM tokens from subscribed users"""
    token = request.json.get("token")
    if not token:
        return jsonify({"error": "No token provided"}), 400

    tokens = []
    if os.path.exists(TOKENS_FILE):
        with open(TOKENS_FILE, "r") as f:
            try:
                tokens = json.load(f)
            except json.JSONDecodeError:
                tokens = []

    if token not in tokens:
        tokens.append(token)
        with open(TOKENS_FILE, "w") as f:
            json.dump(tokens, f, indent=2)
        print(f"[INFO] New subscriber added. Total: {len(tokens)}")

    return jsonify({"status": "success", "total_subscribers": len(tokens)})

    webbrowser.open("http://127.0.0.1:5000")

if __name__ == "__main__":
    app.run(debug=True)
